import {
  CheckSquare,
  ChevronRight,
  Code,
  FileText,
  Heading1,
  Heading2,
  Heading3,
  Image,
  Info,
  List,
  ListOrdered,
  Minus,
  Music,
  Quote,
  Type,
} from 'lucide-react'
import type { SlashItem } from './types'

export const SLASH_ITEMS: SlashItem[] = [
  {
    type: 'p',
    title: 'blocks.slash.p.title',
    description: 'blocks.slash.p.description',
    icon: Type,
    group: 'basic',
    keywords: ['text', 'текст', 'paragraph', 'абзац', 'p'],
  },
  {
    type: 'h1',
    title: 'blocks.slash.h1.title',
    description: 'blocks.slash.h1.description',
    icon: Heading1,
    group: 'basic',
    keywords: ['h1', 'заголовок', 'heading', 'title', '1'],
  },
  {
    type: 'h2',
    title: 'blocks.slash.h2.title',
    description: 'blocks.slash.h2.description',
    icon: Heading2,
    group: 'basic',
    keywords: ['h2', 'подзаголовок', 'heading', 'subtitle', '2'],
  },
  {
    type: 'h3',
    title: 'blocks.slash.h3.title',
    description: 'blocks.slash.h3.description',
    icon: Heading3,
    group: 'basic',
    keywords: ['h3', 'заголовок', 'heading', 'small', '3'],
  },
  {
    type: 'todo',
    title: 'blocks.slash.todo.title',
    description: 'blocks.slash.todo.description',
    icon: CheckSquare,
    group: 'basic',
    keywords: ['todo', 'task', 'чекбокс', 'задача', 'список', 'check'],
  },
  {
    type: 'bullet',
    title: 'blocks.slash.bullet.title',
    description: 'blocks.slash.bullet.description',
    icon: List,
    group: 'basic',
    keywords: ['bullet', 'list', 'список', 'маркер', 'точка'],
  },
  {
    type: 'numbered',
    title: 'blocks.slash.numbered.title',
    description: 'blocks.slash.numbered.description',
    icon: ListOrdered,
    group: 'basic',
    keywords: ['number', 'numbered', 'цифры', '1', 'нумерация'],
  },
  {
    type: 'toggle',
    title: 'blocks.slash.toggle.title',
    description: 'blocks.slash.toggle.description',
    icon: ChevronRight,
    group: 'advanced',
    keywords: ['toggle', 'spoiler', 'спойлер', 'раскрыть', 'скрыть'],
  },
  {
    type: 'callout',
    title: 'blocks.slash.callout.title',
    description: 'blocks.slash.callout.description',
    icon: Info,
    group: 'advanced',
    keywords: ['callout', 'коллаут', 'важно', 'эмодзи', 'info', 'note'],
  },
  {
    type: 'quote',
    title: 'blocks.slash.quote.title',
    description: 'blocks.slash.quote.description',
    icon: Quote,
    group: 'advanced',
    keywords: ['quote', 'цитата', 'высказывание'],
  },
  {
    type: 'code',
    title: 'blocks.slash.code.title',
    description: 'blocks.slash.code.description',
    icon: Code,
    group: 'advanced',
    keywords: ['code', 'код', 'snippet', 'программа', 'js', 'ts'],
  },
  {
    type: 'divider',
    title: 'blocks.slash.divider.title',
    description: 'blocks.slash.divider.description',
    icon: Minus,
    group: 'advanced',
    keywords: ['divider', 'line', 'линия', 'разделитель', 'hr'],
  },
  {
    type: 'image',
    title: 'blocks.slash.image.title',
    description: 'blocks.slash.image.description',
    icon: Image,
    group: 'advanced',
    keywords: ['image', 'картинка', 'фото', 'рисунок', 'img', 'picture', 'photo'],
  },
  {
    type: 'audio',
    title: 'blocks.slash.audio.title',
    description: 'blocks.slash.audio.description',
    icon: Music,
    group: 'advanced',
    keywords: ['audio', 'аудио', 'звук', 'музыка', 'плеер', 'mp3', 'sound', 'voice'],
  },
  {
    type: 'pdf',
    title: 'blocks.slash.pdf.title',
    description: 'blocks.slash.pdf.description',
    icon: FileText,
    group: 'advanced',
    keywords: ['pdf', 'документ', 'пдф', 'файл', 'document'],
  },
]
