import {
  CheckSquare,
  ChevronRight,
  Code,
  FileText,
  Heading1,
  Heading2,
  Heading3,
  Image,
  Info,
  List,
  ListOrdered,
  Minus,
  Music,
  Quote,
  Type,
} from 'lucide-react'
import type { SlashItem } from './types'

export const SLASH_ITEMS: SlashItem[] = [
  {
    type: 'p',
    title: 'Текст',
    description: 'Обычный абзац текста',
    icon: Type,
    group: 'basic',
    keywords: ['text', 'текст', 'paragraph', 'абзац', 'p'],
  },
  {
    type: 'h1',
    title: 'Заголовок 1',
    description: 'Крупный заголовок раздела',
    icon: Heading1,
    group: 'basic',
    keywords: ['h1', 'заголовок', 'heading', 'title', '1'],
  },
  {
    type: 'h2',
    title: 'Заголовок 2',
    description: 'Средний заголовок подраздела',
    icon: Heading2,
    group: 'basic',
    keywords: ['h2', 'подзаголовок', 'heading', 'subtitle', '2'],
  },
  {
    type: 'h3',
    title: 'Заголовок 3',
    description: 'Небольшой заголовок секции',
    icon: Heading3,
    group: 'basic',
    keywords: ['h3', 'заголовок', 'heading', 'small', '3'],
  },
  {
    type: 'todo',
    title: 'Список задач',
    description: 'Чекбокс с вычёркиванием выполненного',
    icon: CheckSquare,
    group: 'basic',
    keywords: ['todo', 'task', 'чекбокс', 'задача', 'список', 'check'],
  },
  {
    type: 'bullet',
    title: 'Маркированный список',
    description: 'Простой список с точками',
    icon: List,
    group: 'basic',
    keywords: ['bullet', 'list', 'список', 'маркер', 'точка'],
  },
  {
    type: 'numbered',
    title: 'Нумерованный список',
    description: 'Список с автоматической нумерацией',
    icon: ListOrdered,
    group: 'basic',
    keywords: ['number', 'numbered', 'цифры', '1', 'нумерация'],
  },
  {
    type: 'toggle',
    title: 'Раскрывающийся спойлер',
    description: 'Блок, который можно скрыть или развернуть',
    icon: ChevronRight,
    group: 'advanced',
    keywords: ['toggle', 'spoiler', 'спойлер', 'раскрыть', 'скрыть'],
  },
  {
    type: 'callout',
    title: 'Цитата-коллаут',
    description: 'Выделенный блок с эмодзи и акцентом',
    icon: Info,
    group: 'advanced',
    keywords: ['callout', 'коллаут', 'важно', 'эмодзи', 'info', 'note'],
  },
  {
    type: 'quote',
    title: 'Цитата',
    description: 'Оформленная цитата с боковой линией',
    icon: Quote,
    group: 'advanced',
    keywords: ['quote', 'цитата', 'высказывание'],
  },
  {
    type: 'code',
    title: 'Блок кода',
    description: 'Моноширинный блок кода',
    icon: Code,
    group: 'advanced',
    keywords: ['code', 'код', 'snippet', 'программа', 'js', 'ts'],
  },
  {
    type: 'divider',
    title: 'Разделитель',
    description: 'Тонкая горизонтальная черта',
    icon: Minus,
    group: 'advanced',
    keywords: ['divider', 'line', 'линия', 'разделитель', 'hr'],
  },
  {
    type: 'image',
    title: 'Изображение',
    description: 'Загрузить картинку или вставить по ссылке',
    icon: Image,
    group: 'advanced',
    keywords: ['image', 'картинка', 'фото', 'рисунок', 'img', 'picture', 'photo'],
  },
  {
    type: 'audio',
    title: 'Аудиозапись',
    description: 'Встроить аудиофайл с плеером',
    icon: Music,
    group: 'advanced',
    keywords: ['audio', 'аудио', 'звук', 'музыка', 'плеер', 'mp3', 'sound', 'voice'],
  },
  {
    type: 'pdf',
    title: 'PDF Документ',
    description: 'Встроить PDF файл с предпросмотром',
    icon: FileText,
    group: 'advanced',
    keywords: ['pdf', 'документ', 'пдф', 'файл', 'document'],
  },
]
