import type { SearchCandidate } from '../../data'
import type { MovieDetails } from './tmdb'

export type FallbackMovie = SearchCandidate & {
  details: MovieDetails
}

export const FALLBACK_MOVIES: FallbackMovie[] = [
  {
    id: '107',
    title: 'Большой куш',
    subtitle: 'Snatch',
    description:
      'Четырехпалый Фрэнки должен переправить краденый алмаз из Англии в США своему боссу Эви. По дороге он попадает в водоворот нелегальных боксерских поединков и криминальных разборок.',
    imageUrl: 'https://image.tmdb.org/t/p/w500/56mOJth6DJ6JhgoEdojPpY00vnm.jpg',
    year: 2000,
    tags: ['Криминал', 'Комедия'],
    score: '8.3',
    details: {
      id: '107',
      title: 'Большой куш',
      originalTitle: 'Snatch',
      tagline: 'У них есть план. И это всё, что у них есть.',
      overview:
        'Четырехпалый Фрэнки должен переправить краденый алмаз в США. В Лондоне он оказывается втянутым в махинации с подпольным боксом, где заправляет Турецкий (Джейсон Стэйтем) и цыган Микки (Брэд Питт).',
      runtimeMinutes: 104,
      releaseDate: '2000-09-01',
      status: 'Released',
      score: '8.3',
      votes: 9400,
      budget: 10000000,
      revenue: 83557872,
      genres: ['Криминал', 'Комедия'],
      countries: [{ iso_3166_1: 'GB', name: 'Великобритания' }],
      originalLanguage: 'en',
      imageUrl: 'https://image.tmdb.org/t/p/w500/56mOJth6DJ6JhgoEdojPpY00vnm.jpg',
      backdropUrl: 'https://image.tmdb.org/t/p/w1280/4HWAQu28LD2Ed0utNdND4RSxAJf.jpg',
      imdbId: 'tt0208092',
      homepage: null,
    },
  },
  {
    id: '98',
    title: 'Карты, деньги, два ствола',
    subtitle: 'Lock, Stock and Two Smoking Barrels',
    description:
      'Четверо молодых парней накопили каждый по 25 тысяч фунтов, чтобы один из них мог сесть за карточный стол с опытным шулером по кличке Топор.',
    imageUrl: 'https://image.tmdb.org/t/p/w500/8kOWDBK6XlPUzckuHDo3wwVRFwt.jpg',
    year: 1998,
    tags: ['Криминал', 'Комедия'],
    score: '8.2',
    details: {
      id: '98',
      title: 'Карты, деньги, два ствола',
      originalTitle: 'Lock, Stock and Two Smoking Barrels',
      tagline: 'Они поставили всё на кон.',
      overview:
        'Четверо друзей проигрывают криминальному авторитету крупную сумму. На возврат долга есть всего неделя, и парни решают ограбить грабителей.',
      runtimeMinutes: 107,
      releaseDate: '1998-08-28',
      status: 'Released',
      score: '8.2',
      votes: 6800,
      budget: 1350000,
      revenue: 28149832,
      genres: ['Криминал', 'Комедия'],
      countries: [{ iso_3166_1: 'GB', name: 'Великобритания' }],
      originalLanguage: 'en',
      imageUrl: 'https://image.tmdb.org/t/p/w500/8kOWDBK6XlPUzckuHDo3wwVRFwt.jpg',
      backdropUrl: null,
      imdbId: 'tt0120735',
      homepage: null,
    },
  },
  {
    id: '522627',
    title: 'Джентльмены',
    subtitle: 'The Gentlemen',
    description:
      'Успешный выпускник Оксфорда придумал дерзкую схему нелегального обогащения с использованием поместий обедневшей английской аристократии.',
    imageUrl: 'https://image.tmdb.org/t/p/w500/jtrhTYB7xSrJxR1vusu99nvnZ1g.jpg',
    year: 2019,
    tags: ['Криминал', 'Боевик', 'Комедия'],
    score: '7.8',
    details: {
      id: '522627',
      title: 'Джентльмены',
      originalTitle: 'The Gentlemen',
      tagline: 'Криминал со вкусом.',
      overview:
        'Американец Микки Пирсон построил в Лондоне высокодоходную империю марихуаны. Решив продать бизнес, он сталкивается с чередой шантажистов, бандитов и эксцентричных тренеров.',
      runtimeMinutes: 113,
      releaseDate: '2019-12-03',
      status: 'Released',
      score: '7.8',
      votes: 5600,
      budget: 22000000,
      revenue: 115171795,
      genres: ['Криминал', 'Боевик', 'Комедия'],
      countries: [
        { iso_3166_1: 'GB', name: 'Великобритания' },
        { iso_3166_1: 'US', name: 'США' },
      ],
      originalLanguage: 'en',
      imageUrl: 'https://image.tmdb.org/t/p/w500/jtrhTYB7xSrJxR1vusu99nvnZ1g.jpg',
      backdropUrl: null,
      imdbId: 'tt8988020',
      homepage: null,
    },
  },
  {
    id: '637649',
    title: 'Гнев человеческий',
    subtitle: 'Wrath of Man',
    description:
      'Эйч — загадочный и немногословный джентльмен, устроившийся в инкассаторскую службу, перевозящую миллионы долларов по Лос-Анджелесу.',
    imageUrl: 'https://image.tmdb.org/t/p/w500/M7RBR2vDC37A9A3Xm6aW7Z95p.jpg',
    year: 2021,
    tags: ['Боевик', 'Криминал', 'Триллер'],
    score: '7.6',
    details: {
      id: '637649',
      title: 'Гнев человеческий',
      originalTitle: 'Wrath of Man',
      tagline: 'Джейсон Стэйтем вернёт долг сполна.',
      overview:
        'Загадочный Эйч (Джейсон Стэйтем) устраивается в инкассаторскую компанию с одной лишь целью — найти людей, виновных в гибели его сына, и покарать каждого.',
      runtimeMinutes: 119,
      releaseDate: '2021-04-22',
      status: 'Released',
      score: '7.6',
      votes: 4900,
      budget: 40000000,
      revenue: 104000000,
      genres: ['Боевик', 'Криминал', 'Триллер'],
      countries: [
        { iso_3166_1: 'US', name: 'США' },
        { iso_3166_1: 'GB', name: 'Великобритания' },
      ],
      originalLanguage: 'en',
      imageUrl: 'https://image.tmdb.org/t/p/w500/M7RBR2vDC37A9A3Xm6aW7Z95p.jpg',
      backdropUrl: null,
      imdbId: 'tt11083552',
      homepage: null,
    },
  },
  {
    id: '4108',
    title: 'Перевозчик',
    subtitle: 'The Transporter',
    description:
      'Бывший спецназовец Фрэнк Мартин имеет три непреложных правила: никогда не менять условий сделки, никаких имен и никогда не смотреть, что в посылке.',
    imageUrl: 'https://image.tmdb.org/t/p/w500/9UjWpB3YI8eUa4q5F4gV8h7t1.jpg',
    year: 2002,
    tags: ['Боевик', 'Криминал', 'Триллер'],
    score: '7.0',
    details: {
      id: '4108',
      title: 'Перевозчик',
      originalTitle: 'The Transporter',
      tagline: 'Правила созданы для того, чтобы их нарушать.',
      overview:
        'Фрэнк Мартин (Джейсон Стэйтем) перевозит любые грузы быстро и без лишних вопросов. Но однажды мешок в багажнике начинает шевелиться...',
      runtimeMinutes: 92,
      releaseDate: '2002-10-02',
      status: 'Released',
      score: '7.0',
      votes: 5200,
      budget: 21000000,
      revenue: 43928932,
      genres: ['Боевик', 'Криминал', 'Триллер'],
      countries: [
        { iso_3166_1: 'FR', name: 'Франция' },
        { iso_3166_1: 'US', name: 'США' },
      ],
      originalLanguage: 'en',
      imageUrl: 'https://image.tmdb.org/t/p/w500/9UjWpB3YI8eUa4q5F4gV8h7t1.jpg',
      backdropUrl: null,
      imdbId: 'tt0293662',
      homepage: null,
    },
  },
  {
    id: '157336',
    title: 'Интерстеллар',
    subtitle: 'Interstellar',
    description:
      'Когда засуха, пыльные бури и вымирание растений приводят человечество к продовольственному кризису, коллектив исследователей и ученых отправляется сквозь червоточину.',
    imageUrl: 'https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
    year: 2014,
    tags: ['Фантастика', 'Драма', 'Приключения'],
    score: '8.6',
    details: {
      id: '157336',
      title: 'Интерстеллар',
      originalTitle: 'Interstellar',
      tagline: 'Следующий шаг человечества станет величайшим.',
      overview:
        'Наше время на Земле подошло к концу, команда исследователей берет на себя самую важную миссию в истории человечества: путешествовать за пределы нашей галактики, чтобы узнать, есть ли у человечества будущее среди звезд.',
      runtimeMinutes: 169,
      releaseDate: '2014-11-05',
      status: 'Released',
      score: '8.6',
      votes: 35000,
      budget: 165000000,
      revenue: 701729206,
      genres: ['Фантастика', 'Драма', 'Приключения'],
      countries: [
        { iso_3166_1: 'US', name: 'США' },
        { iso_3166_1: 'GB', name: 'Великобритания' },
      ],
      originalLanguage: 'en',
      imageUrl: 'https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
      backdropUrl: null,
      imdbId: 'tt0816692',
      homepage: null,
    },
  },
  {
    id: '27205',
    title: 'Начало',
    subtitle: 'Inception',
    description:
      'Кобб — талантливый вор, лучший из лучших в опасном искусстве извлечения: он крадет ценные секреты из глубин подсознания во время сна.',
    imageUrl: 'https://image.tmdb.org/t/p/w500/edv5CZvWj09upOsy2Y6IwDhK8bt.jpg',
    year: 2010,
    tags: ['Боевик', 'Фантастика', 'Приключения'],
    score: '8.4',
    details: {
      id: '27205',
      title: 'Начало',
      originalTitle: 'Inception',
      tagline: 'Твой разум — место преступления.',
      overview:
        'Дом Кобб крадет секреты из снов влиятельных людей. Теперь ему предстоит совершить невозможное: не украсть мысль, а внедрить новую.',
      runtimeMinutes: 148,
      releaseDate: '2010-07-15',
      status: 'Released',
      score: '8.4',
      votes: 36000,
      budget: 160000000,
      revenue: 836836967,
      genres: ['Боевик', 'Фантастика', 'Приключения'],
      countries: [
        { iso_3166_1: 'US', name: 'США' },
        { iso_3166_1: 'GB', name: 'Великобритания' },
      ],
      originalLanguage: 'en',
      imageUrl: 'https://image.tmdb.org/t/p/w500/edv5CZvWj09upOsy2Y6IwDhK8bt.jpg',
      backdropUrl: null,
      imdbId: 'tt1375666',
      homepage: null,
    },
  },
  {
    id: '550',
    title: 'Бойцовский клуб',
    subtitle: 'Fight Club',
    description:
      'Терзаемый хронической бессонницей клерк встречает некоего Тайлера Дёрдена, харизматичного торговца мылом с извращенной философией.',
    imageUrl: 'https://image.tmdb.org/t/p/w500/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg',
    year: 1999,
    tags: ['Драма', 'Триллер'],
    score: '8.4',
    details: {
      id: '550',
      title: 'Бойцовский клуб',
      originalTitle: 'Fight Club',
      tagline: 'Интриги. Хаос. Мыло.',
      overview:
        'Страдающий бессонницей офисный работник знакомится с торговцем мылом Тайлером Дёрденом. Они организуют подпольный бойцовский клуб, который стремительно перерастает в нечто гораздо большее.',
      runtimeMinutes: 139,
      releaseDate: '1999-10-15',
      status: 'Released',
      score: '8.4',
      votes: 28000,
      budget: 63000000,
      revenue: 100853753,
      genres: ['Драма', 'Триллер'],
      countries: [{ iso_3166_1: 'US', name: 'США' }],
      originalLanguage: 'en',
      imageUrl: 'https://image.tmdb.org/t/p/w500/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg',
      backdropUrl: null,
      imdbId: 'tt0137523',
      homepage: null,
    },
  },
  {
    id: '155',
    title: 'Тёмный рыцарь',
    subtitle: 'The Dark Knight',
    description:
      'Бэтмен поднимает ставки в войне с криминалом. При помощи лейтенанта Джима Гордона и прокурора Харви Дента он намерен очистить улицы от преступности.',
    imageUrl: 'https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
    year: 2008,
    tags: ['Боевик', 'Драма', 'Криминал'],
    score: '8.5',
    details: {
      id: '155',
      title: 'Тёмный рыцарь',
      originalTitle: 'The Dark Knight',
      tagline: 'Добро пожаловать в мир без правил.',
      overview:
        'В Готэме появляется Джокер — гений хаоса, который ставит город на колени и заставляет Бэтмена балансировать на грани между героем и линчевателем.',
      runtimeMinutes: 152,
      releaseDate: '2008-07-16',
      status: 'Released',
      score: '8.5',
      votes: 32000,
      budget: 185000000,
      revenue: 1004558444,
      genres: ['Боевик', 'Драма', 'Криминал'],
      countries: [
        { iso_3166_1: 'US', name: 'США' },
        { iso_3166_1: 'GB', name: 'Великобритания' },
      ],
      originalLanguage: 'en',
      imageUrl: 'https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
      backdropUrl: null,
      imdbId: 'tt0468569',
      homepage: null,
    },
  },
  {
    id: '680',
    title: 'Криминальное чтиво',
    subtitle: 'Pulp Fiction',
    description:
      'Двое бандитов Винсент Вега и Джулс Винфилд ведут философские беседы в перерывах между разборками и решением проблем с должниками криминального босса Марселласа Уоллеса.',
    imageUrl: 'https://image.tmdb.org/t/p/w500/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg',
    year: 1994,
    tags: ['Криминал', 'Триллер'],
    score: '8.5',
    details: {
      id: '680',
      title: 'Криминальное чтиво',
      originalTitle: 'Pulp Fiction',
      tagline: 'Только в кинотеатрах.',
      overview:
        'Нелинейная история о криминальном мире Лос-Анджелеса: два киллера, боксер Бутч, жена криминального босса Миа Уоллес и парочка грабителей в закусочной.',
      runtimeMinutes: 154,
      releaseDate: '1994-09-10',
      status: 'Released',
      score: '8.5',
      votes: 27000,
      budget: 8000000,
      revenue: 213928762,
      genres: ['Криминал', 'Триллер'],
      countries: [{ iso_3166_1: 'US', name: 'США' }],
      originalLanguage: 'en',
      imageUrl: 'https://image.tmdb.org/t/p/w500/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg',
      backdropUrl: null,
      imdbId: 'tt0110912',
      homepage: null,
    },
  },
  {
    id: '278',
    title: 'Побег из Шоушенка',
    subtitle: 'The Shawshank Redemption',
    description:
      'Успешный банкир Энди Дюфрейн обвинен в убийстве собственной жены и ее любовника. Оказавшись в тюрьме Шоушенк, он сталкивается с жестокостью и беззаконием.',
    imageUrl: 'https://image.tmdb.org/t/p/w500/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg',
    year: 1994,
    tags: ['Драма', 'Криминал'],
    score: '8.7',
    details: {
      id: '278',
      title: 'Побег из Шоушенка',
      originalTitle: 'The Shawshank Redemption',
      tagline: 'Страх держит в плену. Надежда дарует свободу.',
      overview:
        'История несправедливо осужденного банкира Энди Дюфрейна, сохранившего человечность и надежду на протяжении десятилетий за решеткой.',
      runtimeMinutes: 142,
      releaseDate: '1994-09-23',
      status: 'Released',
      score: '8.7',
      votes: 27000,
      budget: 25000000,
      revenue: 28341469,
      genres: ['Драма', 'Криминал'],
      countries: [{ iso_3166_1: 'US', name: 'США' }],
      originalLanguage: 'en',
      imageUrl: 'https://image.tmdb.org/t/p/w500/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg',
      backdropUrl: null,
      imdbId: 'tt0111161',
      homepage: null,
    },
  },
  {
    id: '603',
    title: 'Матрица',
    subtitle: 'The Matrix',
    description: 'Жизнь Томаса Андерсона разделена на две части: днем он самый обычный офисный служащий, а ночью — хакер по имени Нео.',
    imageUrl: 'https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg',
    year: 1999,
    tags: ['Боевик', 'Фантастика'],
    score: '8.2',
    details: {
      id: '603',
      title: 'Матрица',
      originalTitle: 'The Matrix',
      tagline: 'Добро пожаловать в реальный мир.',
      overview:
        'Хакер Нео узнает, что привычный мир — иллюзия, созданная машинами, поработившими человечество. Он решает присоединиться к повстанцам.',
      runtimeMinutes: 136,
      releaseDate: '1999-03-30',
      status: 'Released',
      score: '8.2',
      votes: 25000,
      budget: 63000000,
      revenue: 467222728,
      genres: ['Боевик', 'Фантастика'],
      countries: [
        { iso_3166_1: 'US', name: 'США' },
        { iso_3166_1: 'AU', name: 'Австралия' },
      ],
      originalLanguage: 'en',
      imageUrl: 'https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg',
      backdropUrl: null,
      imdbId: 'tt0133093',
      homepage: null,
    },
  },
]

export const searchFallbackMovies = (query: string): SearchCandidate[] => {
  const q = query.trim().toLowerCase()
  if (!q) return FALLBACK_MOVIES.slice(0, 8)
  return FALLBACK_MOVIES.filter(
    (m) =>
      m.title.toLowerCase().includes(q) ||
      m.subtitle.toLowerCase().includes(q) ||
      m.description.toLowerCase().includes(q) ||
      m.tags.some((t) => t.toLowerCase().includes(q)),
  )
}

export const getFallbackMovieDetails = (id: string): MovieDetails | null => {
  const found = FALLBACK_MOVIES.find((m) => m.id === id)
  return found ? found.details : null
}
